name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

  merge_group:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.21.0
          cache: npm

      - run: npm ci

      - name: Lint
        run: npx biome ci

  typecheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v6.0.0
        with:
          node-version: 22.21.0
          cache: npm

      - run: npm ci
      - name: Typecheck
        run: npm run typecheck
